import React from 'react';
import Layout from '../components/Layout';

const IndexPage = (): JSX.Element => (
  <Layout>
    <button>Hello</button>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
    <h1>Index</h1>
  </Layout>
);

export default IndexPage;
